/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmcrdr.dialog;

import cmcrdr.event.EventInstance;

/**
 *
 * @author Hyunsuk (David) Chung (DavidChung89@gmail.com)
 */
public class EventLogInstance extends DialogInstance {
          
    /**
     * Case ID that is generated by this dialog
     */
    private int generatedCaseId;  
    
    /**
     * Event Instance of this log
     */
    private EventInstance eventInstance;  
        
    /**
     * Constructor
     */
    public EventLogInstance() {
        
        super(DialogInstance.EVENT_TYPE);
    }
     /**
     * Constructor
     * @param eventLog the event instance to use as the basis of the new instance
     */
    public EventLogInstance(EventLogInstance eventLog) {
        super(eventLog);
        
    }
        
    /**
     *
     * @param caseId
     */
    @Override
    public void setGeneratedCaseId(int caseId){
        this.generatedCaseId = caseId;
    }

    /**
     *
     * @return
     */
    @Override
    public int getGeneratedCaseId(){
        return this.generatedCaseId;
    }
        
    /**
     *
     * @param eventInstance
     */
    @Override
    public void setEventInstance(EventInstance eventInstance){
        this.eventInstance = eventInstance;
    }

    /**
     *
     * @return
     */
    @Override
    public EventInstance getEventInstance(){
        return this.eventInstance;
    }

    @Override
    public String toString(){
       return this.getDialogId() + " " + this.getDialogTag() + this.getEventInstance().toString();
    }
}
